/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import * as React from 'react';

import { IHelloworldData } from './helloworld.data';
import { IHelloworldProps } from './helloworld.props.autogenerated';

export interface IHelloworldViewProps extends IHelloworldProps<IHelloworldData> {}

/**
 *
 * Helloworld component
 * @extends {React.PureComponent<IHelloworldProps<IHelloworldData>>}
 */
class Helloworld extends React.PureComponent<IHelloworldProps<IHelloworldData>> {
    public render(): JSX.Element | null {
        return this.props.renderView(this.props);
    }
}

export default Helloworld;
